/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as DescadastrarRouteImport } from './routes/descadastrar'
import { Route as ComoSeCandidatarRouteImport } from './routes/como-se-candidatar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DescadastrarRoute = DescadastrarRouteImport.update({
  id: '/descadastrar',
  path: '/descadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoSeCandidatarRoute = ComoSeCandidatarRouteImport.update({
  id: '/como-se-candidatar',
  path: '/como-se-candidatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/como-se-candidatar': typeof ComoSeCandidatarRoute
  '/descadastrar': typeof DescadastrarRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/como-se-candidatar': typeof ComoSeCandidatarRoute
  '/descadastrar': typeof DescadastrarRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/como-se-candidatar': typeof ComoSeCandidatarRoute
  '/descadastrar': typeof DescadastrarRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/como-se-candidatar'
    | '/descadastrar'
    | '/politica-de-privacidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/como-se-candidatar'
    | '/descadastrar'
    | '/politica-de-privacidade'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/como-se-candidatar'
    | '/descadastrar'
    | '/politica-de-privacidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComoSeCandidatarRoute: typeof ComoSeCandidatarRoute
  DescadastrarRoute: typeof DescadastrarRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descadastrar': {
      id: '/descadastrar'
      path: '/descadastrar'
      fullPath: '/descadastrar'
      preLoaderRoute: typeof DescadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-se-candidatar': {
      id: '/como-se-candidatar'
      path: '/como-se-candidatar'
      fullPath: '/como-se-candidatar'
      preLoaderRoute: typeof ComoSeCandidatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComoSeCandidatarRoute: ComoSeCandidatarRoute,
  DescadastrarRoute: DescadastrarRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
